trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    contents: '**'  # Copy all files
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy website files to staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish artifact'

